apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: demo-volumesnapshotclass-santricity
driver: santricity.block.csi.ibm.com
deletionPolicy: Delete
parameters:
  csi.storage.k8s.io/snapshotter-secret-name: santricity-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: default

  # Optional: initial snapshot repository group size, as % of base volume.
  # Used only when no eligible snapshot group exists and the driver must create one.
  # Valid range: 1..100. Default when omitted: 20.
  initial_repo_group_size_pct: "25"
