apiVersion: v1
kind: Pod
metadata:
  name: pvc-mounter
spec:
  containers:
  - name: app
    image: docker.io/debian:trixie-backports
    command: ["sh","-c","while true; do df -h /data; sleep 300; done"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: demo-pvc-santricity