kind: Secret
apiVersion: v1
metadata:
  name:  solidfire-secret
  namespace: santricity
type: Opaque
stringData:
  management_address: 192.168.1.34  # Array management addresses, SolidFire MVIP
  username: admin                   # Array username
  verify_ssl: "false"               # (Optional) Enable/disable SSL certificate verification (False by default)
  # port_set: PortSet               # Not used with SolidFire.
data:
  password: YWRtaW4=               # base64 array password; "admin" for demo purposes; echo -n 'admin' | base64
